# Generated by Django 3.2.8 on 2021-10-26 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('gender', models.CharField(max_length=15)),
                ('dob', models.CharField(max_length=24)),
                ('age', models.IntegerField(default=18)),
                ('track', models.CharField(max_length=50)),
                ('mentor', models.CharField(max_length=50)),
                ('goals', models.TextField()),
            ],
        ),
    ]
